<a href="https://colab.research.google.com/github/SeishiroInoue/diveintocode_machine_learning/blob/main/NumPy_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 問題1

AB = [0+0+6 -2+4+27 -1+(-16)+(-3)] [0+0+12 8+(-10)+54 4+40+(-6)] [0+0+(-18) 14+16+(-81) 7+(-64)+9] = [6 29 -20] [12 52 38] [-18 -51 -48]

In [2]:
# 問題2

import numpy as np

a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

np.matmul(a_ndarray, b_ndarray)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [3]:
np.dot(a_ndarray, b_ndarray)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [4]:
a_ndarray @ b_ndarray

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [7]:
for k in range(3):
  AB = a_ndarray[0][k] * b_ndarray[k][0]

print(AB)

6


In [8]:
# 問題4

def scratch(A,B):
  c = np.zeros((len(A[0]), len(A)))
  
  for i in range(len(A[0])):
    for j in range(len(A)):
      for k in range(len(A[0])):
        c[i][j] =  c[i][j] + A[i][k] * B[k][j]
  return c
  
print(scratch(a_ndarray,b_ndarray))

[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


In [10]:
# 問題5

d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

def scratch_if(A,B):
  c = np.zeros((len(A[0]), len(A)))
  if len(A) == len(A[0]):
    for i in range(len(A[0])):
      for j in range(len(A)):
        for k in range(len(A[0])):
          c[i][j] =  c[i][j] + A[i][k] * B[k][j]
    return c
  else:
     print("入力される形に問題があります。")

In [11]:
# 問題6

a_ndarray.T @ b_ndarray

array([[ 14,  69, -40],
       [ 16,  66,  34],
       [-18, -63, -36]])